# Generated by Django 6.1.1 on 2026-10-05 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcar', '0002_alter_especialidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='consultas', through='vetcar.DetalleReceta', to='vetcar.medicamento'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
