# Generated by Django 6.1 on 2026-10-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcar', '0003_consulta_medicamentos_detallereceta_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
