# Generated by Django 6.1 on 2026-09-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
