# Generated by Django 6.1 on 2026-09-13 23:38

import django.core.validators
import django.db.models.deletion
import uuid
import vetcar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('VACUNACION', 'Vacunación')], editable=False, max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=12)),
                ('mascota_nombre', models.CharField(max_length=80)),
                ('dueno_nombre', models.CharField(max_length=100)),
                ('dueno_dni', models.CharField(max_length=8)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ANULACION', 'Anulación'), ('ELIMINACION', 'Eliminación')], max_length=15)),
                ('estado_anterior', models.CharField(blank=True, max_length=12)),
                ('estado_nuevo', models.CharField(blank=True, max_length=12)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de atención',
                'verbose_name_plural': 'Auditorías de atenciones',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_id', models.PositiveIntegerField()),
                ('mascota_nombre', models.CharField(max_length=80)),
                ('dueno_nombre', models.CharField(max_length=100)),
                ('dueno_dni', models.CharField(max_length=8)),
                ('accion', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=4)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de mascota',
                'verbose_name_plural': 'Auditorías de mascotas',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$', 'Este campo solo admite letras y espacios.')])),
                ('telefono', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^9\\d{8}$', 'El teléfono debe tener 9 dígitos y empezar con 9.')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, validators=[vetcar.models.validar_fecha_no_futura])),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(150)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('atencion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vetcar.atencion')),
                ('motivo', models.CharField(max_length=200)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], max_length=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-fecha'],
            },
            bases=('vetcar.atencion',),
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('atencion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vetcar.atencion')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Vacunación',
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['-fecha'],
            },
            bases=('vetcar.atencion',),
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vetcar.persona')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener exactamente 8 dígitos numéricos.')])),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'ordering': ['nombre'],
            },
            bases=('vetcar.persona',),
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_cronicas', models.TextField(blank=True)),
                ('seguro_veterinario', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_clinica', to='vetcar.mascota')),
            ],
            options={
                'verbose_name': 'Ficha clínica',
                'verbose_name_plural': 'Fichas clínicas',
            },
        ),
        migrations.AddField(
            model_name='atencion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='vetcar.mascota'),
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razas', to='vetcar.especie')),
            ],
            options={
                'ordering': ['especie__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='vetcar.raza'),
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dosis', models.CharField(max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='vetcar.medicamento')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_receta', to='vetcar.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='vetcar.dueno'),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vetcar.persona')),
                ('colegiatura', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,4}-\\d{4,6}$', 'Formato de colegiatura inválido, ej. "ABC-12345".')])),
                ('fecha_ingreso', models.DateField(validators=[vetcar.models.validar_fecha_no_futura])),
                ('especialidades', models.ManyToManyField(related_name='veterinarios', to='vetcar.especialidad')),
            ],
            options={
                'ordering': ['nombre'],
            },
            bases=('vetcar.persona',),
        ),
        migrations.CreateModel(
            name='SeguimientoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_asignacion', models.DateField(validators=[vetcar.models.validar_fecha_no_futura])),
                ('rol', models.CharField(choices=[('TITULAR', 'Veterinario titular'), ('INTERCONSULTA', 'Interconsulta / especialista')], max_length=15)),
                ('activo', models.BooleanField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='vetcar.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='vetcar.veterinario')),
            ],
            options={
                'verbose_name': 'Seguimiento clínico',
                'verbose_name_plural': 'Seguimientos clínicos',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='veterinarios_seguimiento',
            field=models.ManyToManyField(blank=True, related_name='mascotas_seguimiento', through='vetcar.SeguimientoClinico', to='vetcar.veterinario'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='vetcar.veterinario'),
        ),
        migrations.AddConstraint(
            model_name='raza',
            constraint=models.UniqueConstraint(fields=('nombre', 'especie'), name='raza_unica_por_especie'),
        ),
        migrations.AddConstraint(
            model_name='detallereceta',
            constraint=models.UniqueConstraint(fields=('consulta', 'medicamento'), name='medicamento_unico_por_consulta'),
        ),
        migrations.AddConstraint(
            model_name='seguimientoclinico',
            constraint=models.UniqueConstraint(fields=('mascota', 'veterinario', 'rol'), name='seguimiento_unico'),
        ),
    ]
