# Generated by Django 6.1.1 on 2026-09-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['especie', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('colegiatura', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='vetcar.dueno')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='vetcar.raza')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='vetcar.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='vetcar.veterinario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
