# Generated by Django 6.1.1 on 2026-09-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=15)),
                ('vehiculo_descripcion', models.CharField(max_length=100)),
                ('vehiculo_placa', models.CharField(max_length=10)),
                ('mecanico', models.CharField(choices=[('Carlos Ramírez', 'Carlos Ramírez'), ('Luis Fernández', 'Luis Fernández')], max_length=100)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], default='En espera', max_length=20)),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('fecha_entrega', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_atencion', '-hora_atencion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='taller.cita')),
            ],
        ),
    ]
